name: parking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  flashy_tab_bar2: ^0.0.10
  flutter_map: ^7.0.2
  cloud_firestore: ^5.4.3
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
